### ISSUE TITLE
Requirements don't exist

### ISSUE THREAD

**Issue by KaizerFox** [FLUORESCENTXX/NetflixAccountGenerator#4]
PS C:\Users\yes\Documents\FluroNFGen UPDATE 1.0.1\FluroNFGen UPDATE 1.0.1> pip install random
ERROR: Could not find a version that satisfies the requirement random (from versions: none)
ERROR: No matching distribution found for random
PS C:\Users\yes\Documents\FluroNFGen UPDATE 1.0.1\FluroNFGen UPDATE 1.0.1> pip install string
ERROR: Could not find a version that satisfies the requirement string (from versions: none)
ERROR: No matching distribution found for string
PS C:\Users\yes\Documents\FluroNFGen UPDATE 1.0.1\FluroNFGen UPDATE 1.0.1> pip install time
ERROR: Could not find a version that satisfies the requirement time (from versions: none)
ERROR: No matching distribution found for time

and also  File "C:\Users\yes\Documents\FluroNFGen UPDATE 1.0.1\FluroNFGen UPDATE 1.0.1\main.py", line 5, in <module>
    from msedge.selenium_tools import Edge, EdgeOptions
ModuleNotFoundError: No module named 'msedge'

i think you forgot to say which python version to use, im using the latest. its probably causing problems

**Comment by FLUORESCENTXX** [comment]
Latest ofc
